### ISSUE TITLE
0.6.2 Pre Deployment QA

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/elcid#1244]
For OHC: 

- [ ] Deploy to Heroku
- [ ] All stories pass on Heroku
- [ ] Deploy to ELCIDT
- [ ] All stories pass on ELCIDT

For clinical team:

- [ ] All stories pass on Heroku
- [ ] All stories pass on ELCIDT
