### ISSUE TITLE
Calendar issues that need fixing (summary)

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#289]
In order of priority:
- [x] date format incorrect - should be DD/MM/YYYY - #275 
- [x] default calendar option should be today for diagnosis, antimicrobial & investigation - #274 
- [x] calendar doesn't disappear when date picked - #288 
- [x] reduce size of calendar - this obscures too many fields below - #273 
- [x] Date inconsistency - #308
