### ISSUE TITLE
Discharge Diagnosis - Patient Flow

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#362]
Alongside Presenting Complaint I discussed this at length with @GabPoll today.
Agreement along the following lines.

We consider there to be three levels of Diagnosis
- Working diagnosis: already captured perfectly by the Diagnosis Modal
- Discharge diagnosis: added at the time of discharge
- Final Diagnosis: set post-discharge as part of a review process

Implementation of the additional two levels of discharge has three main parts
- [x] Discharge Diagnosis Modal #363
- [x] Generation of a Review List for Final Diagnosis #364
- [x] Final Diagnosis Modal #365
