### ISSUE TITLE
Patient Flow - OPAT Edition

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#406]
Excellent discussion with @jonnylambourne today to clarify this.
Inspired by the very nice Accept/Refuse button on OPAT-Referrals.

Patient Flow Through System:

OPAT Referral: 
- [x] Accept / RefuseButton 
  - If accept > OPAT-Current
  - If decline: 
  - [x] Why Refuse Modal 
  - [x] Set OPAT Review Date #187 

OPAT Current:
- [x] Completed IV Therapy Button 
  User then selects either
- Switch to oral therapy: Patient moves to OPAT-Follow Up
- [x] User to complete "Finished IV Modal" #402
- Completed antibiotic treatment: Set OPAT Review Date #187 
- [x] User to complete "Finished Antibiotics Modal" #403
- [x] User to complete "Finished OPAT Modal" #404

OPAT Follow-Up
- [x] Switch back to IV Therapy button
- [x] User to complete "Finished Antibiotic Modal" #403
- Moves user back to OPAT Current
- [x] Completed antibiotic treatment: Set OPAT Review Date #187 
- [x] User to complete "Finished Antibiotics Modal" #403
- [x] User to complete "Finished OPAT Modal" #404

OPAT Review
- [ ] OPAT Outcomes button #405
- Once completed patient is removed from list
